# Generated by Django 2.2.3 on 2019-07-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppicks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toprom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('rating', models.CharField(max_length=10)),
                ('Dir', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Topthrill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('rating', models.CharField(max_length=10)),
                ('Dir', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=500)),
            ],
        ),
    ]
