# Generated by Django 2.2.3 on 2019-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('card_text', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('rating', models.CharField(max_length=10)),
                ('Dir', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=500)),
            ],
        ),
    ]
