# Generated by Django 2.2.3 on 2019-07-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolly', '0002_hotstories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotStories',
        ),
    ]
