# Generated by Django 2.2.3 on 2019-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolly', '0003_delete_hotstories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
