# Generated by Django 2.2.3 on 2019-07-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolly', '0004_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BiggestFilmYearly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Business', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HighestOpeningWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Release_Date', models.CharField(max_length=100)),
                ('OpeningWeek', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='huncr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(max_length=10)),
                ('Movie', models.CharField(max_length=100)),
                ('Business', models.CharField(max_length=100)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Romance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Thriller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(max_length=10)),
                ('Movie', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TopFilmFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(max_length=10)),
                ('Franchise', models.CharField(max_length=100)),
                ('Business', models.CharField(max_length=20)),
                ('films', models.IntegerField()),
                ('topfilm', models.CharField(max_length=100)),
            ],
        ),
    ]
