# Generated by Django 2.2.3 on 2019-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolly', '0005_action_biggestfilmyearly_comedy_highestopeningweek_huncr_romance_thriller_topday_topfilmfranchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestGrossers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('Business', models.CharField(max_length=100)),
            ],
        ),
    ]
