# Generated by Django 2.2.3 on 2019-07-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolly', '0006_highestgrossers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highestgrossers',
            old_name='Year',
            new_name='Rank',
        ),
    ]
